apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lab-asciidoc-sample

resources:
- namespace.yaml

bases:
- https://github.com/openshift-homeroom/lab-asciidoc-sample/.workshop?ref=1.9

configMapGenerator:
- name: spawner-environ
  behavior: merge
  env: settings.txt
